import type { MageConfig } from "../types/game";

export const MAGES: MageConfig[] = [
  // ── RARE ─────────────────────────────────────────────────────────────
  {
    id: "wind-whisperer",
    name: "Wind Whisperer",
    type: "wind",
    rarity: "rare",
    atk: 1,
    interval: 4,
    dps: 0.25,
    priceTon: 0,
    image: "/mages/wind-whisperer.jpg",
    baseDps: 10,
    upgradeCost: 0,
    level: 1,
    emoji: "🌀",
    attackColor: "#34d399",
  },
  {
    id: "storm-weaver",
    name: "Storm Weaver",
    type: "lightning",
    rarity: "rare",
    atk: 3,
    interval: 10,
    dps: 0.30,
    priceTon: 0.5,
    image: "/mages/storm-weaver.jpg",
    baseDps: 12,
    upgradeCost: 50,
    level: 1,
    emoji: "⚡",
    attackColor: "#60a5fa",
  },
  {
    id: "frost-weaver",
    name: "Frost Weaver",
    type: "ice",
    rarity: "rare",
    atk: 7,
    interval: 20,
    dps: 0.35,
    priceTon: 0.8,
    image: "/mages/frost-weaver.jpg",
    baseDps: 14,
    upgradeCost: 80,
    level: 1,
    emoji: "❄️",
    attackColor: "#7dd3fc",
  },
  {
    id: "pyreclastic-arcanist",
    name: "Pyreclastic Arcanist",
    type: "fire",
    rarity: "rare",
    atk: 2,
    interval: 5,
    dps: 0.40,
    priceTon: 1.2,
    image: "/mages/pyreclastic-arcanist.jpg",
    baseDps: 16,
    upgradeCost: 120,
    level: 1,
    emoji: "🔥",
    attackColor: "#f97316",
  },
  {
    id: "aether-scholar",
    name: "Aether Scholar",
    type: "wind",
    rarity: "rare",
    atk: 1,
    interval: 2,
    dps: 0.50,
    priceTon: 1.5,
    image: "/mages/aether-scholar.jpg",
    baseDps: 20,
    upgradeCost: 150,
    level: 1,
    emoji: "✨",
    attackColor: "#a3e635",
  },
  // ── EPIC ─────────────────────────────────────────────────────────────
  {
    id: "elara-void-weaver",
    name: "Elara, Void Weaver",
    type: "wind",
    rarity: "epic",
    atk: 3,
    interval: 5,
    dps: 0.60,
    priceTon: 3.0,
    image: "/mages/elara-void-weaver.jpg",
    baseDps: 24,
    upgradeCost: 300,
    level: 1,
    emoji: "🌌",
    attackColor: "#a855f7",
  },
  {
    id: "aethel-thunderlord",
    name: "Aethel, Thunderlord",
    type: "lightning",
    rarity: "epic",
    atk: 7,
    interval: 10,
    dps: 0.70,
    priceTon: 3.8,
    image: "/mages/aethel-thunderlord.jpg",
    baseDps: 28,
    upgradeCost: 380,
    level: 1,
    emoji: "⚡",
    attackColor: "#facc15",
  },
  {
    id: "korvin-thunderclap",
    name: "Korvin, Thunderclap",
    type: "lightning",
    rarity: "epic",
    atk: 4,
    interval: 5,
    dps: 0.80,
    priceTon: 4.5,
    image: "/mages/korvin-thunderclap.jpg",
    baseDps: 32,
    upgradeCost: 450,
    level: 1,
    emoji: "🌩️",
    attackColor: "#818cf8",
  },
  {
    id: "kaeleda-void-dancer",
    name: "Kaeleda, Void Dancer",
    type: "wind",
    rarity: "epic",
    atk: 9,
    interval: 10,
    dps: 0.90,
    priceTon: 5.2,
    image: "/mages/kaeleda-void-dancer.jpg",
    baseDps: 36,
    upgradeCost: 520,
    level: 1,
    emoji: "💜",
    attackColor: "#c084fc",
  },
  {
    id: "kalen-inferno-blaze",
    name: "Kalen, Inferno Blaze",
    type: "fire",
    rarity: "epic",
    atk: 1,
    interval: 1,
    dps: 1.00,
    priceTon: 6.0,
    image: "/mages/kalen-inferno-blaze.jpg",
    baseDps: 40,
    upgradeCost: 600,
    level: 1,
    emoji: "🔥",
    attackColor: "#ef4444",
  },
  // ── LEGENDARY ────────────────────────────────────────────────────────
  {
    id: "silas-starsinger",
    name: "Silas, Starsinger",
    type: "wind",
    rarity: "legendary",
    atk: 5,
    interval: 4,
    dps: 1.25,
    priceTon: 12.0,
    image: "/mages/silas-starsinger.jpg",
    baseDps: 50,
    upgradeCost: 1200,
    level: 1,
    emoji: "⭐",
    attackColor: "#fde68a",
  },
  {
    id: "lyra-cosmic-weaver",
    name: "Lyra, Cosmic Weaver",
    type: "wind",
    rarity: "legendary",
    atk: 3,
    interval: 2,
    dps: 1.50,
    priceTon: 14.0,
    image: "/mages/lyra-cosmic-weaver.jpg",
    baseDps: 60,
    upgradeCost: 1400,
    level: 1,
    emoji: "🌟",
    attackColor: "#fbbf24",
  },
  {
    id: "aethel-abyss-weaver",
    name: "Aethel, Abyss Weaver",
    type: "wind",
    rarity: "legendary",
    atk: 7,
    interval: 4,
    dps: 1.75,
    priceTon: 16.0,
    image: "/mages/aethel-abyss-weaver.jpg",
    baseDps: 70,
    upgradeCost: 1600,
    level: 1,
    emoji: "🌑",
    attackColor: "#e879f9",
  },
  {
    id: "solaris-chronos-shaper",
    name: "Solaris, Chronos Shaper",
    type: "fire",
    rarity: "legendary",
    atk: 2,
    interval: 1,
    dps: 2.00,
    priceTon: 18.0,
    image: "/mages/solaris-chronos-shaper.jpg",
    baseDps: 80,
    upgradeCost: 1800,
    level: 1,
    emoji: "☀️",
    attackColor: "#fb923c",
  },
  {
    id: "lyra-emerald-chronomancer",
    name: "Lyra, Emerald Chronomancer",
    type: "ice",
    rarity: "legendary",
    atk: 5,
    interval: 2,
    dps: 2.50,
    priceTon: 22.0,
    image: "/mages/lyra-emerald-chronomancer.jpg",
    baseDps: 100,
    upgradeCost: 2200,
    level: 1,
    emoji: "💎",
    attackColor: "#34d399",
  },
];

export const getMageDps = (mage: MageConfig): number =>
  Math.floor(mage.baseDps * Math.pow(1.4, mage.level - 1));
